version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 99
  ignore:
    - dependency-name: software.amazon.awssdk:ssm
      update-types:
        - version-update:semver-minor
